---
- name: Add ansible repository.
  apt_repository: repo='ppa:ansible/ansible'

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install Ansible.
  apt: name=ansible state=installed
